<?php 
$this->headTitle('list user');
$this->headLink()->appendStylesheet($this->baseUrl('/css/styleUser.css'));
$this->inlineScript()->appendFile($this->baseUrl('/js/post-form.js'));
$form = $this->userForm;
?>
<script>
   //form Submit action
   
</script>
<!--Upload Form-->
<form>
  <table>
    <tr>
      <td colspan="2">File Upload</td>
    </tr>
    <tr>
      <th>Select File </th>
      <td><input id="csv" name="csv" type="file" /></td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="submit" value="submit"/> 
      </td>
    </tr>
  </table>
</form>