<?php
$this; /* @var $this Zend_View */ 
$this->inlineScript()->prependFile($this->baseUrl('/js/jquery-3.2.1.min.js'));
?>
<!DOCTYPE html>
<html>
<head>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?> 
</head>
<body>
    <?php echo $this->layout()->content; ?>
    <?php echo $this->inlineScript(); ?>
</body>
</html>