<?php 
$this->headTitle('list user');
$this->headLink()->appendStylesheet($this->baseUrl('/css/styleUser.css'));
$this->inlineScript()->appendFile($this->baseUrl('/js/user.js'));
$userForm = $this->userForm;   /* @var $userForm UserController*/
$users = $this->users; /* @var $users UserController */

$userName = $userForm->name;
$userNameLabel = $userForm->name->getLabel();

$userAge = $userForm->age;
$userAgeLabel = $userAge->getLabel();

//$userImg = $userForm->img;
//$userImgLabel = $userImg->getLabel();

$userAdd = $userForm->Add;

$userUpdate = $userForm->Update;

?>
<div id='control'>
	<form enctype="multipart/form-data" method="post" id="formData">
		<table id='user-form' class="form-table">
			<tr>
				<td><?php echo $userNameLabel ?></td>
				<td><?php echo $userForm->name ?></td>
			</tr>
			<tr>
				<td><?php echo $userAgeLabel ?></td>
				<td><?php echo $userForm->age ?></td>
			</tr>
			<tr>
				<td><?php echo $userForm->id; ?></td>
			</tr>
			<tr>
				<td rowspan = "2" id="message-error">
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $userAdd ?>
					<?php echo $userUpdate ?>
				</td>
			</tr>
		</table>
	</form>
</div>
<div id='view'>
	<table id='user-list' class="list-table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Age</th>
				<th>User Images</th>
			</tr>
		</thead>
		<tbody id="user-view">
			<?php foreach ($users as $user) : 
					$userId = $user['id'];
					$userName = $user['name'];
					$userAge = $user['age'];
					$userImg = $user['img'];
			?>
				<tr id="user<?php echo $userId ?>" data-id="<?php echo $userId ?>" class="user-id">
					<td class="user-name"><?php echo $userName  ?></td>
					<td class="user-age"><?php echo $userAge  ?></td>
					<td><?php echo $userImg  ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>